import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Navbar } from "../components/navbar/Navbar";
import styles from "../styles/App.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>Main page</main>
    </div>
  );
};

export default Home;
